# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='git_url',
            field=models.CharField(max_length=240, unique=True),
        ),
    ]
