# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0002_auto_20170414_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
