# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0004_auto_20170414_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('In Progress', 'In Progress'), ('Failed', 'Failed'), ('Complete', 'Complete')], default='Created', max_length=50)),
                ('error_log', models.TextField(blank=True, default='')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_jobs', to='app_server.Commit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('ext', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app_server.Project')),
            ],
        ),
        migrations.CreateModel(
            name='FileMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.FloatField(default=0)),
                ('file_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_to', to='app_server.File')),
                ('file_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_from', to='app_server.File')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('In Progress', 'In Progress'), ('Failed', 'Failed'), ('Complete', 'Complete')], default='Created', max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('total_commits', models.IntegerField(default=0)),
                ('processed_commits', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_jobs', to='app_server.Project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='filemapping',
            name='project_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_mappings', to='app_server.ProjectJob'),
        ),
        migrations.AddField(
            model_name='commitjob',
            name='project_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_jobs', to='app_server.ProjectJob'),
        ),
        migrations.AlterUniqueTogether(
            name='filemapping',
            unique_together=set([('project_job', 'file_from', 'file_to')]),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('project', 'path')]),
        ),
    ]
