# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0005_auto_20170415_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('Source', 'Source'), ('Config', 'Config'), ('Other', 'Other')], max_length=50),
        ),
    ]
